version: '3'
services:
 proxy:
  build: ./
  networks:
   - web1_default
   - web2_default
  ports:
   - 80:80
   - 443:443


networks:
 example1:
   external:
     name: web1_default
 example2:
   external:
      name: web2_default