version: '3'
services:
 proxy:
  build: ./

  ports:
   - 80:80
   - 443:443
  networks: 
   - example1
   - example2
   
# networks:
#   example1:
#    external:
#    name: example1_default
#   example2:
#     external:
#     name: example2_default
