version: '2'
services:
  app:
    build: .
    image: flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 80:80
    networks:
      - a
      - b
  redis:
    image: redis:4.0.11-alpine
    networks:
      - b
    volumes:
      - dbdata:/data

networks:
  a:
  b:

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/redis'